#!/usr/bin/env python

import sys

from rqt_bag_helper.rqt_bag_helper import RqtBagHelper
from rqt_gui.main import Main

plugin = 'rqt_bag_helper'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
